In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [2]:
import numpy as np
import pandas as pd

In [6]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [7]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [8]:
# 1D Array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# 2D Array
array_2d = np.array([[1, 2, 3], 
                     [4, 5, 6]])
print("\n2D Array:")
print(array_2d)

# 3D Array
array_3d = np.array([[[1, 2], 
                      [3, 4]],
                     [[5, 6], 
                      [7, 8]]])
print("\n3D Array:")
print(array_3d)

# 4D Array
array_4d = np.array([[[[1, 2], 
                       [3, 4]],
                      [[5, 6], 
                       [7, 8]]],
                     
                     [[[9, 10], 
                       [11, 12]],
                      [[13, 14], 
                       [15, 16]]]])

print("\n4D Array:")
print(array_4d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

4D Array:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [9]:
# 1D Array using arange()
array_1d = np.arange(1, 6)
print("1D Array:")
print(array_1d)


# 2D Array using reshape()
array_2d = np.arange(1, 7).reshape(2, 3)
print("\n2D Array:")
print(array_2d)


# 3D Array using reshape()
array_3d = np.arange(1, 13).reshape(2, 2, 3)
print("\n3D Array:")
print(array_3d)


# 4D Array using reshape()
array_4d = np.arange(1, 17).reshape(2, 2, 2, 2)
print("\n4D Array:")
print(array_4d)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

4D Array:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


# create array using ones and zeros

In [10]:
# Creating arrays using ones()

# 1D array of ones
ones_1d = np.ones(5)
print("1D Ones Array:")
print(ones_1d)

# 2D array of ones
ones_2d = np.ones((2, 3))
print("\n2D Ones Array:")
print(ones_2d)

# 3D array of ones
ones_3d = np.ones((2, 2, 3))
print("\n3D Ones Array:")
print(ones_3d)


# Creating arrays using zeros()

# 1D array of zeros
zeros_1d = np.zeros(5)
print("\n1D Zeros Array:")
print(zeros_1d)

# 2D array of zeros
zeros_2d = np.zeros((2, 3))
print("\n2D Zeros Array:")
print(zeros_2d)

# 3D array of zeros
zeros_3d = np.zeros((2, 2, 3))
print("\n3D Zeros Array:")
print(zeros_3d)

1D Ones Array:
[1. 1. 1. 1. 1.]

2D Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]]

3D Ones Array:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

1D Zeros Array:
[0. 0. 0. 0. 0.]

2D Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]

3D Zeros Array:
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


# using random

In [11]:
# Random arrays

# Random values between 0 and 1
random_array = np.random.rand(3, 3)

print("Random Array:")
print(random_array)


# Random integer values
random_int = np.random.randint(1, 100, size=(3, 3))

print("\nRandom Integer Array:")
print(random_int)

Random Array:
[[0.05080796 0.58833823 0.54234767]
 [0.00751687 0.39329315 0.90427734]
 [0.6253386  0.33034429 0.63696754]]

Random Integer Array:
[[74 98 35]
 [ 2 52 99]
 [90 31 14]]


# using linspace

In [12]:
# Creating array using linspace()

# Generates 10 evenly spaced numbers between 0 and 100
linear_array = np.linspace(0, 100, 10)

print("Linspace Array:")
print(linear_array)

Linspace Array:
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


# create 1D array of tip from tips dataframe

In [13]:
# Creating 1D array from tip column

tip_array = np.array(tips['tip'])

print("1D Array of tip:")
print(tip_array)

1D Array of tip:
[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2

# create 2D array of tip and total_bill form tips dataframe

In [14]:
# Creating 2D array from tip and total_bill columns

tip_bill_array = np.array(tips[['tip', 'total_bill']])

print("2D Array of tip and total_bill:")
print(tip_bill_array)

2D Array of tip and total_bill:
[[ 1.01 16.99]
 [ 1.66 10.34]
 [ 3.5  21.01]
 [ 3.31 23.68]
 [ 3.61 24.59]
 [ 4.71 25.29]
 [ 2.    8.77]
 [ 3.12 26.88]
 [ 1.96 15.04]
 [ 3.23 14.78]
 [ 1.71 10.27]
 [ 5.   35.26]
 [ 1.57 15.42]
 [ 3.   18.43]
 [ 3.02 14.83]
 [ 3.92 21.58]
 [ 1.67 10.33]
 [ 3.71 16.29]
 [ 3.5  16.97]
 [ 3.35 20.65]
 [ 4.08 17.92]
 [ 2.75 20.29]
 [ 2.23 15.77]
 [ 7.58 39.42]
 [ 3.18 19.82]
 [ 2.34 17.81]
 [ 2.   13.37]
 [ 2.   12.69]
 [ 4.3  21.7 ]
 [ 3.   19.65]
 [ 1.45  9.55]
 [ 2.5  18.35]
 [ 3.   15.06]
 [ 2.45 20.69]
 [ 3.27 17.78]
 [ 3.6  24.06]
 [ 2.   16.31]
 [ 3.07 16.93]
 [ 2.31 18.69]
 [ 5.   31.27]
 [ 2.24 16.04]
 [ 2.54 17.46]
 [ 3.06 13.94]
 [ 1.32  9.68]
 [ 5.6  30.4 ]
 [ 3.   18.29]
 [ 5.   22.23]
 [ 6.   32.4 ]
 [ 2.05 28.55]
 [ 3.   18.04]
 [ 2.5  12.54]
 [ 2.6  10.29]
 [ 5.2  34.81]
 [ 1.56  9.94]
 [ 4.34 25.56]
 [ 3.51 19.49]
 [ 3.   38.01]
 [ 1.5  26.41]
 [ 1.76 11.24]
 [ 6.73 48.27]
 [ 3.21 20.29]
 [ 2.   13.81]
 [ 1.98 11.02]
 [ 3.76 18.29]
 [ 2.64 

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [15]:
# Example 1

array1 = np.array([1, 2, 3, 4, 5])

print("Array 1:")
print(array1)

print("Dimension:", array1.ndim)
print("Shape:", array1.shape)
print("Size:", array1.size)
print("Item Size:", array1.itemsize)


# Example 2

array2 = np.array([[10, 20, 30],
                   [40, 50, 60]])

print("\nArray 2:")
print(array2)

print("Dimension:", array2.ndim)
print("Shape:", array2.shape)
print("Size:", array2.size)
print("Item Size:", array2.itemsize)

Array 1:
[1 2 3 4 5]
Dimension: 1
Shape: (5,)
Size: 5
Item Size: 8

Array 2:
[[10 20 30]
 [40 50 60]]
Dimension: 2
Shape: (2, 3)
Size: 6
Item Size: 8


# change data type and memory size of any np-array using astype()

In [16]:
# Original array
arr = np.array([1, 2, 3, 4, 5])

print("Original Array:")
print(arr)

print("Original Data Type:", arr.dtype)
print("Original Memory Size:", arr.itemsize)


# Change datatype to float
float_arr = arr.astype(float)

print("\nAfter changing to float:")
print(float_arr)

print("New Data Type:", float_arr.dtype)
print("New Memory Size:", float_arr.itemsize)


# Change datatype to integer of smaller size
int_arr = arr.astype(np.int8)

print("\nAfter changing to int8:")
print(int_arr)

print("New Data Type:", int_arr.dtype)
print("New Memory Size:", int_arr.itemsize)

Original Array:
[1 2 3 4 5]
Original Data Type: int64
Original Memory Size: 8

After changing to float:
[1. 2. 3. 4. 5.]
New Data Type: float64
New Memory Size: 8

After changing to int8:
[1 2 3 4 5]
New Data Type: int8
New Memory Size: 1


# create 2 same dimensional array and do scalar and vector operations

In [17]:
# Creating two same dimensional arrays

array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)


# Scalar operations
print("\nScalar Addition:")
print(array1 + 5)

print("\nScalar Multiplication:")
print(array1 * 2)


# Vector operations
print("\nVector Addition:")
print(array1 + array2)

print("\nVector Subtraction:")
print(array1 - array2)

print("\nVector Multiplication:")
print(array1 * array2)

print("\nVector Division:")
print(array1 / array2)

Array 1:
[10 20 30 40]

Array 2:
[1 2 3 4]

Scalar Addition:
[15 25 35 45]

Scalar Multiplication:
[20 40 60 80]

Vector Addition:
[11 22 33 44]

Vector Subtraction:
[ 9 18 27 36]

Vector Multiplication:
[ 10  40  90 160]

Vector Division:
[10. 10. 10. 10.]


# find minimun and maximum tip

In [18]:
# Convert tip column into numpy array

tip_array = np.array(tips['tip'])

# Find minimum and maximum tip

minimum_tip = np.min(tip_array)
maximum_tip = np.max(tip_array)

print("Minimum Tip:", minimum_tip)
print("Maximum Tip:", maximum_tip)

Minimum Tip: 1.0
Maximum Tip: 10.0


# find average total_bill and average tip

In [19]:
# Find average total_bill and average tip

average_total_bill = np.mean(tips['total_bill'])
average_tip = np.mean(tips['tip'])

print("Average Total Bill:", average_total_bill)
print("Average Tip:", average_tip)

Average Total Bill: 19.78594262295082
Average Tip: 2.99827868852459


# find median total_bill

In [20]:
# Find median total_bill

median_total_bill = np.median(tips['total_bill'])

print("Median Total Bill:", median_total_bill)

Median Total Bill: 17.795


# find standard deviasion and variance of tip

In [21]:
# Convert tip column into numpy array

tip_array = np.array(tips['tip'])

# Standard deviation
std_tip = np.std(tip_array)

# Variance
var_tip = np.var(tip_array)

print("Standard Deviation of Tip:", std_tip)
print("Variance of Tip:", var_tip)

Standard Deviation of Tip: 1.3807999538298954
Variance of Tip: 1.9066085124966412


# find log values of tip

In [22]:
# Find log values of tip

tip_array = np.array(tips['tip'])

log_tip = np.log(tip_array)

print("Log values of tip:")
print(log_tip)

Log values of tip:
[0.00995033 0.5068176  1.25276297 1.19694819 1.28370777 1.54968791
 0.69314718 1.137833   0.67294447 1.17248214 0.53649337 1.60943791
 0.45107562 1.09861229 1.10525683 1.36609165 0.51282363 1.31103188
 1.25276297 1.20896035 1.40609699 1.01160091 0.80200159 2.0255132
 1.1568812  0.85015093 0.69314718 0.69314718 1.45861502 1.09861229
 0.37156356 0.91629073 1.09861229 0.89608802 1.18478998 1.28093385
 0.69314718 1.12167756 0.83724752 1.60943791 0.80647587 0.93216408
 1.11841492 0.27763174 1.7227666  1.09861229 1.60943791 1.79175947
 0.71783979 1.09861229 0.91629073 0.95551145 1.64865863 0.44468582
 1.46787435 1.25561604 1.09861229 0.40546511 0.56531381 1.90657514
 1.16627094 0.69314718 0.68309684 1.32441896 0.97077892 1.14740245
 0.90421815 0.         0.69813472 0.73716407 0.67803354 1.09861229
 1.1442228  1.60943791 0.78845736 0.22314355 1.1249296  1.38629436
 1.09861229 0.99694863 1.09861229 1.22377543 0.60431597 1.60943791
 0.70803579 1.64287269 0.69314718 1.38629436

# apply round, floor and ceil operation on tip array

In [23]:
# Apply round, floor and ceil operations on tip array

tip_array = np.array(tips['tip'])

print("Original Tip Values:")
print(tip_array[:10])


print("\nRounded Values:")
print(np.round(tip_array[:10]))


print("\nFloor Values:")
print(np.floor(tip_array[:10]))


print("\nCeil Values:")
print(np.ceil(tip_array[:10]))

Original Tip Values:
[1.01 1.66 3.5  3.31 3.61 4.71 2.   3.12 1.96 3.23]

Rounded Values:
[1. 2. 4. 3. 4. 5. 2. 3. 2. 3.]

Floor Values:
[1. 1. 3. 3. 3. 4. 2. 3. 1. 3.]

Ceil Values:
[2. 2. 4. 4. 4. 5. 2. 4. 2. 4.]


# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [24]:
# ==========================
# 1D Array Indexing & Slicing
# ==========================

arr1 = np.array([10, 20, 30, 40, 50])

print("1D Array:", arr1)

# Example 1: First element
print("Example 1:", arr1[0])

# Example 2: Last element
print("Example 2:", arr1[-1])

# Example 3: Second element
print("Example 3:", arr1[1])

# Example 4: Slice first three elements
print("Example 4:", arr1[:3])

# Example 5: Slice last two elements
print("Example 5:", arr1[-2:])


# ==========================
# 2D Array Indexing & Slicing
# ==========================

arr2 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print("\n2D Array:")
print(arr2)

# Example 1: First row
print("Example 1:", arr2[0])

# Example 2: First element
print("Example 2:", arr2[0,0])

# Example 3: Last element
print("Example 3:", arr2[2,2])

# Example 4: First column
print("Example 4:", arr2[:,0])

# Example 5: First two rows
print("Example 5:")
print(arr2[:2])


# ==========================
# 3D Array Indexing & Slicing
# ==========================

arr3 = np.array([
    [[1,2,3],
     [4,5,6]],

    [[7,8,9],
     [10,11,12]]
])

print("\n3D Array:")
print(arr3)

# Example 1: First block
print("Example 1:")
print(arr3[0])

# Example 2: First element
print("Example 2:", arr3[0,0,0])

# Example 3: Last element
print("Example 3:", arr3[-1,-1,-1])

# Example 4: First row of second block
print("Example 4:")
print(arr3[1,0])

# Example 5: Slice entire second block
print("Example 5:")
print(arr3[1])

1D Array: [10 20 30 40 50]
Example 1: 10
Example 2: 50
Example 3: 20
Example 4: [10 20 30]
Example 5: [40 50]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Example 1: [1 2 3]
Example 2: 1
Example 3: 9
Example 4: [1 4 7]
Example 5:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Example 1:
[[1 2 3]
 [4 5 6]]
Example 2: 1
Example 3: 12
Example 4:
[7 8 9]
Example 5:
[[ 7  8  9]
 [10 11 12]]


# stacking and spliting

In [27]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

# use hstack() and vstack()

In [28]:
# Horizontal stacking (combine columns)

h_stack = np.hstack((d, e))

print("Horizontal Stack:")
print(h_stack)


# Vertical stacking (combine rows)

v_stack = np.vstack((d, e))

print("\nVertical Stack:")
print(v_stack)

Horizontal Stack:
[[ 0  1  2  3  4  5  6  7  8 28 29 30 31 32 33 34 35 36]
 [ 9 10 11 12 13 14 15 16 17 37 38 39 40 41 42 43 44 45]
 [18 19 20 21 22 23 24 25 26 46 47 48 49 50 51 52 53 54]]

Vertical Stack:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]


# use hsplit() and vsplit()

In [29]:
# Horizontal split

h_split = np.hsplit(d, 3)

print("Horizontal Split:")
for i in h_split:
    print(i)


# Vertical split

v_split = np.vsplit(d, 3)

print("\nVertical Split:")
for i in v_split:
    print(i)

Horizontal Split:
[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]

Vertical Split:
[[0 1 2 3 4 5 6 7 8]]
[[ 9 10 11 12 13 14 15 16 17]]
[[18 19 20 21 22 23 24 25 26]]
